Repository eduNEXT/eox-tenant, pull requests merged in 2024-02, with the labels that each got.

#193 feat: add openedx commitlint.config.js
  commitlint.config.js
Labels: size/s

#196 perf: add Quince support DS-776
  .github/workflows/bump_version.yml
  .github/workflows/commitlint.yml
  .github/workflows/python-publish.yml
  .github/workflows/tests.yml
  Makefile
  README.rst
  eox_tenant/admin.py
  eox_tenant/api/v1/tests/test_microsites.py
  eox_tenant/api/v1/tests/test_routes.py
  eox_tenant/api/v1/tests/test_tenant_config.py
  eox_tenant/async_utils.py
  eox_tenant/edxapp_wrapper/backends/branding_api_l_v1.py
  eox_tenant/management/commands/change_domain.py
  eox_tenant/management/commands/change_signup_sources.py
  eox_tenant/management/commands/create_or_update_tenant_config.py
  eox_tenant/management/commands/edit_microsite_values.py
  eox_tenant/management/commands/synchronize_organizations.py
  eox_tenant/middleware.py
  eox_tenant/models.py
  eox_tenant/pipeline.py
  eox_tenant/settings/production.py
  eox_tenant/settings/test.py
  eox_tenant/signals.py
  eox_tenant/templatetags/ednx.py
  eox_tenant/tenant_wise/proxies.py
  eox_tenant/test/test_async_utils.py
  eox_tenant/test/test_middleware.py
  eox_tenant/test/test_pipeline.py
  eox_tenant/test/test_signals.py
  eox_tenant/test_utils.py
  eox_tenant/utils.py
  requirements/base.txt
  requirements/constraints.txt
  requirements/django32.txt
  requirements/django42.txt
  requirements/pip-tools.txt
  requirements/test.txt
  requirements/tox.txt
  setup.cfg
  setup.py
  tox.ini
Labels: size/l

#197 fix: allow using boolean as values in tenant configs when getting settings by organization
  eox_tenant/models.py
  eox_tenant/tenant_wise/proxies.py
Labels: size/xs
