Repository eduNEXT/eox-tenant, pull requests merged in 2024-04, with the labels that each got.

#195 refactor: inherit from social auth exception
  eox_tenant/pipeline.py
  requirements/base.in
  requirements/base.txt
  requirements/django32.txt
  requirements/django42.txt
  requirements/pip-tools.txt
  requirements/test.txt
  requirements/tox.txt
  setup.cfg
Labels: size/m

#201 Correcting user restriction behavior by sign up source in eox-tenant
  eox_tenant/edxapp_wrapper/backends/edx_auth_n_v1.py
  eox_tenant/settings/common.py
  eox_tenant/settings/production.py
Labels: size/s

#185 feat: separate studio config and handler
  eox_tenant/apps.py
  eox_tenant/constants.py
  eox_tenant/models.py
  eox_tenant/receivers_helpers.py
  eox_tenant/signals.py
  eox_tenant/test/test_receivers_helpers.py
  eox_tenant/test/test_signals.py
Labels: waiting on author
