Repository eduNEXT/eox-tenant, pull requests merged in 2024-06, with the labels that each got.

#206 feat: add support for JWT authentication `DS-959`
  eox_tenant/api/v1/viewsets.py
  eox_tenant/docs/resources/eox-tenant-test.postman_collection.json
  requirements/base.in
  requirements/base.txt
  requirements/django42.txt
  requirements/pip-tools.txt
  requirements/test.txt
  requirements/tox.txt
Labels: size/l

#209 feat: create edx organization when updating course_org_filter `DS-961`
  eox_tenant/settings/common.py
  eox_tenant/utils.py
  requirements/base.in
  requirements/base.txt
  requirements/constraints.txt
  requirements/pip-tools.txt
  requirements/test.txt
Labels: size/s

#213 feat: add api integration test
  eox_tenant/test/tutor/integration_test_tutor.py
Labels: size/s

#212 perf: redwood release support `DS-1011`
  .github/workflows/add_issues_prs_to_dedalo_project.yml
  .github/workflows/commitlint.yml
  .github/workflows/integration-test.yml
  .github/workflows/pr_issue_assignment.yml
  .github/workflows/python-publish.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  README.rst
  commitlint.mjs
  eox_tenant/__init__.py
  eox_tenant/edxapp_wrapper/backends/users_l_v1.py
  eox_tenant/edxapp_wrapper/backends/users_p_v1.py
  eox_tenant/settings/common.py
  eox_tenant/test/tutor/integration_test_tutor.py
  requirements/base.txt
  requirements/constraints.txt
  requirements/pip-tools.txt
  requirements/test.txt
  requirements/tox.txt
  setup.cfg
  setup.py
  tox.ini
Labels: size/m

#214 docs: update changelog and docs
  CHANGELOG.md
  README.rst
Labels: size/s
